/**
 * Multi-Language eBPF Code Generator
 * Generates eBPF programs in different programming languages
 */

export class MultiLanguageGenerator {
  constructor() {
    this.supportedLanguages = {
      c: { name: 'C', extension: '.c', icon: 'C' },
      rust: { name: 'Rust', extension: '.rs', icon: '🦀' },
      go: { name: 'Go', extension: '.go', icon: '🐹' },
      python: { name: 'Python (BCC)', extension: '.py', icon: '🐍' },
      cpp: { name: 'C++', extension: '.cpp', icon: 'C++' },
      zig: { name: 'Zig', extension: '.zig', icon: '⚡' }
    };
  }

  /**
   * Generate code in the specified language
   */
  generateCode(nodes, edges, language) {
    switch (language) {
      case 'c':
        return this.generateC(nodes, edges);
      case 'rust':
        return this.generateRust(nodes, edges);
      case 'go':
        return this.generateGo(nodes, edges);
      case 'python':
        return this.generatePython(nodes, edges);
      case 'cpp':
        return this.generateCpp(nodes, edges);
      case 'zig':
        return this.generateZig(nodes, edges);
      default:
        throw new Error(`Unsupported language: ${language}`);
    }
  }

  /**
   * Generate C code (original implementation)
   */
  generateC(nodes, edges) {
    const entryNode = nodes.find(node => node.type === 'attachment');
    if (!entryNode) {
      return '// Error: No program entry point found. Add an Attachment node.';
    }

    return `#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>
#include <linux/if_ether.h>
#include <linux/ip.h>
#include <linux/tcp.h>
#include <linux/udp.h>

// eBPF program generated by Super eBPF Builder
// Entry point: ${entryNode.data?.label || 'Unknown'}

SEC("${entryNode.data?.attachmentType || 'xdp'}")
int ebpf_program(struct ${this.getContextType(entryNode.data?.attachmentType)} *ctx)
{
    // Generated eBPF logic
    ${this.generateLogicC(nodes, edges)}
    
    return XDP_PASS;
}

char _license[] SEC("license") = "GPL";`;
  }

  /**
   * Generate Rust code using aya framework
   */
  generateRust(nodes, edges) {
    const entryNode = nodes.find(node => node.type === 'attachment');
    if (!entryNode) {
      return '// Error: No program entry point found. Add an Attachment node.';
    }

    return `#![no_std]
#![no_main]

use aya_bpf::{
    bindings::xdp_action,
    macros::xdp,
    programs::XdpContext,
};

// eBPF program generated by Super eBPF Builder
// Entry point: ${entryNode.data?.label || 'Unknown'}

#[xdp]
pub fn ebpf_program(ctx: XdpContext) -> u32 {
    match try_ebpf_program(ctx) {
        Ok(ret) => ret,
        Err(_) => xdp_action::XDP_ABORTED,
    }
}

fn try_ebpf_program(ctx: XdpContext) -> Result<u32, u32> {
    // Generated eBPF logic
    ${this.generateLogicRust(nodes, edges)}
    
    Ok(xdp_action::XDP_PASS)
}

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    unsafe { core::hint::unreachable_unchecked() }
}`;
  }

  /**
   * Generate Go code using cilium/ebpf
   */
  generateGo(nodes, edges) {
    const entryNode = nodes.find(node => node.type === 'attachment');
    if (!entryNode) {
      return '// Error: No program entry point found. Add an Attachment node.';
    }

    return `//go:build ignore

package main

import (
    "github.com/cilium/ebpf"
    "github.com/cilium/ebpf/link"
    "github.com/cilium/ebpf/rlimit"
)

// eBPF program generated by Super eBPF Builder
// Entry point: ${entryNode.data?.label || 'Unknown'}

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang ebpf program.c

func main() {
    // Remove memory limit for eBPF
    if err := rlimit.RemoveMemlock(); err != nil {
        panic(err)
    }

    // Load pre-compiled eBPF program
    spec, err := loadEbpf()
    if err != nil {
        panic(err)
    }

    coll, err := ebpf.NewCollection(spec)
    if err != nil {
        panic(err)
    }
    defer coll.Close()

    // Attach the program
    l, err := link.AttachXDP(link.XDPOptions{
        Program:   coll.Programs["ebpf_program"],
        Interface: 1, // Replace with actual interface index
    })
    if err != nil {
        panic(err)
    }
    defer l.Close()

    // Generated eBPF logic in Go userspace
    ${this.generateLogicGo(nodes, edges)}
}`;
  }

  /**
   * Generate Python code using BCC
   */
  generatePython(nodes, edges) {
    const entryNode = nodes.find(node => node.type === 'attachment');
    if (!entryNode) {
      return '# Error: No program entry point found. Add an Attachment node.';
    }

    return `#!/usr/bin/env python3
"""
eBPF program generated by Super eBPF Builder
Entry point: ${entryNode.data?.label || 'Unknown'}
"""

from bcc import BPF
import ctypes as ct

# eBPF C code
bpf_text = """
#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>
#include <linux/if_ether.h>
#include <linux/ip.h>

int ebpf_program(struct ${this.getContextType(entryNode.data?.attachmentType)} *ctx)
{
    // Generated eBPF logic
    ${this.generateLogicC(nodes, edges)}
    
    return XDP_PASS;
}
"""

def main():
    # Load eBPF program
    b = BPF(text=bpf_text)
    
    # Attach to interface (replace "eth0" with actual interface)
    fn = b.load_func("ebpf_program", BPF.XDP)
    b.attach_xdp("eth0", fn, 0)
    
    print("eBPF program loaded and attached")
    print("Press Ctrl+C to exit")
    
    try:
        # Generated Python userspace logic
        ${this.generateLogicPython(nodes, edges)}
        b.trace_print()
    except KeyboardInterrupt:
        pass
    finally:
        b.remove_xdp("eth0", 0)
        print("Program detached")

if __name__ == "__main__":
    main()`;
  }

  /**
   * Generate C++ code
   */
  generateCpp(nodes, edges) {
    const entryNode = nodes.find(node => node.type === 'attachment');
    if (!entryNode) {
      return '// Error: No program entry point found. Add an Attachment node.';
    }

    return `#include <linux/bpf.h>
#include <bpf/bpf_helpers.h>
#include <linux/if_ether.h>
#include <linux/ip.h>
#include <linux/tcp.h>
#include <linux/udp.h>

extern "C" {

// eBPF program generated by Super eBPF Builder
// Entry point: ${entryNode.data?.label || 'Unknown'}

SEC("${entryNode.data?.attachmentType || 'xdp'}")
int ebpf_program(struct ${this.getContextType(entryNode.data?.attachmentType)} *ctx)
{
    // Generated eBPF logic
    ${this.generateLogicC(nodes, edges)}
    
    return XDP_PASS;
}

} // extern "C"

char _license[] SEC("license") = "GPL";`;
  }

  /**
   * Generate Zig code
   */
  generateZig(nodes, edges) {
    const entryNode = nodes.find(node => node.type === 'attachment');
    if (!entryNode) {
      return '// Error: No program entry point found. Add an Attachment node.';
    }

    return `const std = @import("std");
const bpf = @import("bpf");

// eBPF program generated by Super eBPF Builder
// Entry point: ${entryNode.data?.label || 'Unknown'}

export fn ebpf_program(ctx: *${this.getContextTypeZig(entryNode.data?.attachmentType)}) callconv(.C) u32 {
    // Generated eBPF logic
    ${this.generateLogicZig(nodes, edges)}
    
    return bpf.XDP_PASS;
}

comptime {
    @export(ebpf_program, .{ .name = "ebpf_program", .section = "${entryNode.data?.attachmentType || 'xdp'}" });
}`;
  }

  /**
   * Generate build files for each language
   */
  generateBuildFile(language, programName) {
    switch (language) {
      case 'c':
      case 'cpp':
        return this.generateMakefile(language, programName);
      case 'rust':
        return this.generateCargoToml(programName);
      case 'go':
        return this.generateGoMod(programName);
      case 'python':
        return this.generateRequirementsTxt();
      case 'zig':
        return this.generateBuildZig(programName);
      default:
        return '';
    }
  }

  generateMakefile(language, programName) {
    const compiler = language === 'cpp' ? 'clang++' : 'clang';
    const ext = language === 'cpp' ? '.cpp' : '.c';
    
    return `# Makefile for eBPF program (${language.toUpperCase()})
# Generated by Super eBPF Builder
CC = ${compiler}
CFLAGS = -O2 -target bpf -c ${language === 'cpp' ? '-x c++' : ''}

PROGRAM = ${programName}

all: \$(PROGRAM).o

\$(PROGRAM).o: \$(PROGRAM)${ext}
\t\$(CC) \$(CFLAGS) \$(PROGRAM)${ext} -o \$(PROGRAM).o

clean:
\trm -f *.o

install: \$(PROGRAM).o
\tsudo cp \$(PROGRAM).o /sys/fs/bpf/

load: \$(PROGRAM).o
\tsudo bpftool prog load \$(PROGRAM).o /sys/fs/bpf/\$(PROGRAM)

unload:
\tsudo rm -f /sys/fs/bpf/\$(PROGRAM)

.PHONY: all clean install load unload`;
  }

  generateCargoToml(programName) {
    return `[package]
name = "${programName}"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "${programName}"
path = "src/main.rs"

[dependencies]
aya-bpf = "0.1"
aya-log-ebpf = "0.1"

[features]
default = []`;
  }

  generateGoMod(programName) {
    return `module ${programName}

go 1.21

require (
    github.com/cilium/ebpf v0.12.0
)

require (
    golang.org/x/sys v0.10.0 // indirect
)`;
  }

  generateRequirementsTxt() {
    return `bcc>=0.25.0
pyroute2>=0.7.0
psutil>=5.9.0`;
  }

  generateBuildZig(programName) {
    return `const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const exe = b.addExecutable(.{
        .name = "${programName}",
        .root_source_file = .{ .path = "src/main.zig" },
        .target = target,
        .optimize = optimize,
    });

    b.installArtifact(exe);
}`;
  }

  // Helper methods for generating language-specific logic
  generateLogicC(nodes, edges) {
    return '// TODO: Implement flow logic based on nodes and edges\n    bpf_printk("eBPF program executed\\n");';
  }

  generateLogicRust(nodes, edges) {
    return '// TODO: Implement flow logic based on nodes and edges\n    aya_log_ebpf::info!(&ctx, "eBPF program executed");';
  }

  generateLogicGo(nodes, edges) {
    return '// TODO: Implement flow logic based on nodes and edges\n    println("eBPF program loaded successfully")';
  }

  generateLogicPython(nodes, edges) {
    return '# TODO: Implement flow logic based on nodes and edges\n        print("eBPF program executing...")';
  }

  generateLogicZig(nodes, edges) {
    return '// TODO: Implement flow logic based on nodes and edges\n    // bpf.printk("eBPF program executed\\n");';
  }

  getContextType(attachmentType) {
    switch (attachmentType) {
      case 'xdp': return 'xdp_md';
      case 'tc': return '__sk_buff';
      case 'socket': return '__sk_buff';
      case 'kprobe': return 'pt_regs';
      case 'tracepoint': return 'trace_event_raw_*';
      default: return 'xdp_md';
    }
  }

  getContextTypeZig(attachmentType) {
    switch (attachmentType) {
      case 'xdp': return 'bpf.xdp_md';
      case 'tc': return 'bpf.__sk_buff';
      case 'socket': return 'bpf.__sk_buff';
      case 'kprobe': return 'bpf.pt_regs';
      default: return 'bpf.xdp_md';
    }
  }

  getSupportedLanguages() {
    return this.supportedLanguages;
  }
}